version: '3.9'

services:
  gymplanner.webui:
    image: ${DOCKER_REGISTRY-}gymplannerwebui
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq
      - gymloggingdb
    ports:
      - "5000:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA="Y"
      - SA_PASSWORD="MyPass@word"
      - MSSQL_PID=Express
    ports:
      - "1439:1433"

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5673:5672"
      - "15673:15672"

  gymloggingdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA="Y"
      - SA_PASSWORD="MyPass@word"
      - MSSQL_PID=Express
    ports:
      - "1440:1433"
