version: '3.4'

services:
  gymplanner.webui:
    image: ${DOCKER_REGISTRY-}gymplannerwebui
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - sqlserver
      - rabbitmq

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "password"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5673:5672"
      - "15673:15672"
